/**
 * Custom Cloudflare Worker entrypoint.
 *
 * OpenNext generates `.open-next/worker.js` with only a `fetch` handler (plus the
 * Durable Object classes it needs). Cloudflare delivers Cron Triggers to the
 * `scheduled()` handler — NOT to HTTP routes — so without this wrapper the crons
 * declared in wrangler.toml fire into the void and none of the /api/cron/* jobs
 * ever run (reminders, retention purge, onboarding emails, nightly backups).
 *
 * This file re-exports OpenNext's fetch handler (and its DO classes via the
 * `export *`) and adds a `scheduled()` handler that dispatches each cron tick to
 * the matching internal route. Requests are synthesised in-worker, so they carry
 * `x-cloudflare-cron` but NOT `cf-connecting-ip` — exactly what verifyCronAuth
 * (src/lib/cron-auth.ts) treats as a trusted internal cron invocation.
 *
 * `main` in wrangler.toml points here; wrangler bundles `.open-next/worker.js`
 * (which exists after `opennextjs-cloudflare build`) at deploy time.
 */
// @ts-expect-error - generated by `opennextjs-cloudflare build`, absent at typecheck time
import worker from "./.open-next/worker.js";

// Re-export the Durable Object classes (DOQueueHandler, DOShardedTagCache,
// BucketCachePurge, ...) that the generated worker declares. `export *` skips
// the default export, so our own default below wins.
// @ts-expect-error - see import note above
export * from "./.open-next/worker.js";

interface ScheduledController {
  readonly cron: string;
  readonly scheduledTime: number;
}

interface ExecutionCtx {
  waitUntil(promise: Promise<unknown>): void;
}

// Map each declared cron expression (wrangler.toml [triggers]) to the routes it
// should invoke. Keep this in sync with wrangler.toml `crons`.
const CRON_ROUTES: Record<string, string[]> = {
  // Every 15 minutes — appointment reminders (also self-handles the 02:00 backup).
  "*/15 * * * *": ["/api/cron/reminders"],
  // Daily at 02:00 UTC — data-retention purge and onboarding emails.
  "0 2 * * *": ["/api/cron/retention", "/api/cron/onboarding"],
};

// Any absolute origin works — the cron routes don't do host-based routing. We use
// the production workers.dev hostname for clarity in logs.
const INTERNAL_ORIGIN = "https://parkkal-dental.chandran-aathi.workers.dev";

export default {
  ...worker,

  async scheduled(controller: ScheduledController, env: unknown, ctx: ExecutionCtx): Promise<void> {
    const routes = CRON_ROUTES[controller.cron] ?? [];
    if (routes.length === 0) {
      console.error(`[CRON] No routes mapped for cron "${controller.cron}" — check wrangler.toml`);
      return;
    }

    const runs = routes.map(async (path) => {
      const req = new Request(`${INTERNAL_ORIGIN}${path}`, {
        method: "GET",
        headers: { "x-cloudflare-cron": controller.cron },
      });
      try {
        const res = await worker.fetch(req, env, ctx);
        if (!res.ok) {
          console.error(`[CRON] ${path} returned HTTP ${res.status}`);
        } else {
          console.info(`[CRON] ${path} ok (HTTP ${res.status})`);
        }
      } catch (err) {
        console.error(`[CRON] ${path} threw:`, err instanceof Error ? err.message : err);
      }
    });

    // Keep the invocation alive until every job settles.
    await Promise.allSettled(runs);
  },
};
