name = "parkkal-dental"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
assets = { directory = ".open-next/assets" }

[[d1_databases]]
binding = "DB"
database_name = "parkkal-db"
database_id = "9928a95f-17d2-4e84-80a1-c7b30d779704"
migrations_dir = "drizzle/migrations"
